config/routes.rb
TaskManagement::Application.routes.draw do
  root :to=> "home#index"
  match "", :to=>"home#index", :as => "home"


  match "tasklist",:to => "task#index" , :as => "task_list"

  match "new_task", :to => "task#new" , :as => "new_task"
  match "create_task", :to => "task#create" , :as => "create_task"
  match "delete_task/:id" ,:to => "task#delete", :as => "delete_task"
  match "edit_task/:id", :to => "task#edit" , :as => "edit_task"
  match "update_task/:id", :to => "task#update" , :as => "update_task"
  
end

app/models/task.rb
class Task

  include Mongoid::Document
  include Mongoid::Timestamps

  field :name,  type: :String
  field :description, type:  String
  field :completion_date, type:  DateTime
  field :completion_state, type: Integer, :default => 0
  
  embedded_in :user

  validates_presence_of :name
  validate :date_ok?

  def date_ok?
    unless completion_date.is_a?(Date) 
      self.errors.add(:completion_date,"this is not a valid date")
    end
  end

end

app/models/user.rb
class User
  
  include Mongoid::Document
  field :user_name , type: String
  
  embeds_many :tasks do 
    def that_expired      
      self.select{|t|t.completion_date <= DateTime.now && t.completion_state == 0 }
    end
   
    def not_signed_off
      self.select{|t|t.completion_state == 0}      
    end
  end

  accepts_nested_attributes_for :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :check_users
  
  def check_users
      if User.all.length==0
       User.create(:user_name => "Test person")       
       User.last.tasks.push Task.new(:name => "Do some cool task", :completion_date => Date.today.advance(:days=>7) )
       User.last.tasks.push Task.new(:name => "Do some cool task", :completion_date => Date.today.advance(:days=>-17) )
       User.last.tasks.push Task.new(:name => "Do some cool task", :completion_date => Date.today )
       User.last.save
       
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  def index   
    @user = User.first
  end

  def new
    add_edit
  end

  def edit  
    @task = User.first.tasks.find(params[:id])
    render :action => :new
  end

  def update
     
     task = User.first.tasks.find(params[:id])
     task.update_attributes(params[:task])
     task.save
     excluded = User.first.tasks.select{|t| t if t.id.to_s!= params[:id] }
     User.first.tasks = excluded
     User.first.tasks << task          
     User.first.save

     @user = User.first     
     render :action => :index
  end

  def create
    @task = Task.new params[:task]
    @user = User.first
    
    if @task.valid?
      @user.tasks.push @task
      @user.save
      return redirect_to :action => :index 
    end
    render :action => :new
  end

  def delete
     puts "There are #{User.last.tasks.length}"
     tasks = User.first.tasks.select{|t| t if t.id.to_s!= params[:id] }
     User.last.tasks = tasks     
     User.last.save
     puts "There are #{User.last.tasks.length}"
     @user = User.first
     render :action => :index
  end

  private 
  def add_edit
    @task = Task.new
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def menu_options
      ["Create new task", "View all tasks"]
  end

  def normal_date(d)
    return "Not a date" if !d.is_a?(DateTime)
    d.to_formatted_s(:long)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  
  def status_img(status, task_date)
    title =  past_task(task_date)     
    imgname = status.to_s.eql?("0") && title.include?("expired")   ? "/assets/alert.png" : "/assets/tick.png"
    image_tag imgname, :title=>title
  end

  def past_task(task_date)     
     d = (task_date)
     n  = Date.today
     (n-d).to_i >0  ? "This task expired" : ""
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.haml
!!! XML
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title= "Task Management"
    %meta{:"http-equiv" => "Content-Type", :content => "text/html; charset=utf-8"}
    
    = javascript_include_tag "application"
    = stylesheet_link_tag "application"  
    = stylesheet_link_tag "ui-darkness/jquery-ui-1.8.10.custom.css"
    /= javascript_include_tag "jquery"
    /= javascript_include_tag "jquery-ui"
   
    = javascript_include_tag "http://www.google.com/jsapi"   

    = csrf_meta_tag 
      
  %body
    #abslogo
    #abslogo1
    #popup_dialog
	
    #container
      #header
        #top
          #logo
            Task Management
          #user_info
            Hello new user
          
      = render :partial=> "/shared/menu"
         
      #content
        =yield


  :javascript
    var $j = jQuery.noConflict();
    $j(document).ready(  function(){ $j('.datepicker').datepicker(); } )
      

app/views/shared/_header.html.haml
.task_header
  %div
    Manage your Task list from here

  = render :partial => "shared/menu"

app/views/shared/_menu.html.haml
.main_menu
  %ul
    - menu_options.each_with_index do |m,i|
      %li
        = link_to m, i==0 ? new_task_path : task_list_path

app/views/task/index.html.haml
.task_list
  %div
    %table
      %tr
        %th
          Task Name
        %th        
          Description
        %th
          Completion date
        %th
          Status
        %th

      - @user.tasks.each do |t|
        %tr.task_entities
          %td=t.name
          %td=t.description
          %td= normal_date t.completion_date
          %td= status_img(t.completion_state, t.completion_date)
          %td
            =link_to image_tag("/assets/edit.png"), edit_task_path(t)
            =link_to image_tag("/assets/delete.png"), delete_task_path(t)
            

app/views/task/new.html.haml
- current_action = @task.new_record? ? "Create" : "Update"
#main_content  
  .top_content
    #task_form
      %h2 #{current_action} a task here 
      = form_for @task, :url => @task.new_record? ? create_task_path : update_task_path(@task.id) do |f|
        -if @task.errors.any?
          %p.errors
            There are errors on the following fields, please correct them :
            =@task.errors.messages.keys.select{|e| e }.flatten.join(',')
        %ul
          %li
            =f.label :name
            =f.text_field :name
          %li
            =f.label :description
            =f.text_field :description
          %li
            =f.label :completion_date
            =f.text_field :completion_date, :class => "datepicker"
          %li
            .primary_button
              %button{:type=>"submit"} #{current_action} task  